name: flutter_github_trend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.1+1
  bloc: ^8.1.4
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  json_serializable: ^6.8.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
